version: '3.5'

services:
  elasticsearch:
    image: elasticsearch:8.6.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'

  nginx:
    image: nginx
    restart: always
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - "./app:/var/www/html/public"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    environment:
      - NGINX_HOST=localhost
    depends_on:
      - php
    links:
      - php

  php:
    image: php:8.1-fpm
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - "./app:/var/www/html/public"
